### ISSUE TITLE
ARCHITEC

### ISSUE THREAD

**Issue by Luisangelriverosbautista** [SistemasTecTlaxiaco/actividad-3-practica-architect-Luisangelriverosbautista#1]
[Reporte_Architec L.pdf](https://github.com/user-attachments/files/16841761/Reporte_Architec.L.pdf)

**Comment by Kim-Mendoza3** [comment]
Calificacion 19, cumple con la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
